## Learning Objective
- Missing value identification and treatment
    - Create a copy of the dataframe
    - Imputing missing values with different techniques

## Import required libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

##  Load the dataset

In [ ]:
#df = pd.read_csv('app.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/app.csv')
df.head()

Mounted at /content/drive

,App,Rating,Reviews,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,4.1,159,Free,0,Everyone
1,Coloring book moana,3.9,967,Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",4.7,87510,Free,0,Everyone
3,Sketch - Draw & Paint,4.5,215644,Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,4.3,967,Free,0,Everyone

## Check for null values and impute them

In [ ]:
df.isna().sum()

App                0
Rating             8
Reviews            0
Type              16
Price              0
Content Rating     0
dtype: int64

In [ ]:
df.isna().sum()/df.shape[0]*100

App               0.00000
Rating            0.08547
Reviews           0.00000
Type              0.17094
Price             0.00000
Content Rating    0.00000
dtype: float64

- There are some missing values in the rating and type features

## What isnull() function recognises as missing value?

In [ ]:
df_rating = pd.DataFrame({'value' : df['Rating'], 'Missing?' : df['Rating'].isnull()}) 
df_rating[df_rating['Missing?']==True]

      value  Missing?
250     NaN      True
251     NaN      True
420     NaN      True
542     NaN      True
543     NaN      True
756     NaN      True
9351    NaN      True
9352    NaN      True

- Here, only 'NaN' is recognised as missing value
- Depending on the context, we decide what should be a missing value. Like sometimes, zero could considered missing.

## Impute null values

### Method 1:- Drop null values as there are very few of them

In [ ]:
df1 = df.dropna()
df1.isna().sum()

App               0
Rating            0
Reviews           0
Type              0
Price             0
Content Rating    0
dtype: int64

### Method 2:- Replace with mode

In [ ]:
df.mode()

      App  Rating  Reviews  Type Price Content Rating
0  ROBLOX     4.4        2  Free     0       Everyone

In [ ]:
df2 = df.copy() 
cols = ["Rating", "Type"]
df2[cols]=df[cols].fillna(df.mode().iloc[0])

df2.isna().sum()

App               0
Rating            0
Reviews           0
Type              0
Price             0
Content Rating    0
dtype: int64

### Method 3:- Replace with mean/median for continuous column

In [ ]:
df3 = df.copy() 

df3 = df.fillna(df.median())

df3.isna().sum()

App                0
Rating             0
Reviews            0
Type              16
Price              0
Content Rating     0
dtype: int64

---
## Happy Learning :)
---