## Learning Objective
- Normalization and Scaling
  - Min Max scaling
  - Max Absolute scaling
  - Standard scaling

## Import required libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

## Load the dataset

In [ ]:
#df = pd.read_csv('app.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/app.csv')
df.head()

Mounted at /content/drive

,App,Rating,Reviews,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,4.1,159,Free,0,Everyone
1,Coloring book moana,3.9,967,Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",4.7,87510,Free,0,Everyone
3,Sketch - Draw & Paint,4.5,215644,Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,4.3,967,Free,0,Everyone

## 1.  Data Preparation for scaling

### 1.1 Encode categorical features

In [ ]:
## create a copy of the dataframe
df1 = df.copy()

In [ ]:
df_final = pd.get_dummies(df1, columns= ['Type','Content Rating'], drop_first = True)
df_final.head()

,App,Rating,Reviews,Price,Type_Paid,Content Rating_Everyone,Content Rating_Everyone 10+,Content Rating_Mature 17+,Content Rating_Teen,Content Rating_Unrated
0,Photo Editor & Candy Camera & Grid & ScrapBook,4.1,159,0,0,1,0,0,0,0
1,Coloring book moana,3.9,967,0,0,1,0,0,0,0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",4.7,87510,0,0,1,0,0,0,0
3,Sketch - Draw & Paint,4.5,215644,0,0,0,0,0,1,0
4,Pixel Draw - Number Art Coloring Book,4.3,967,0,0,1,0,0,0,0

### 1.2 Drop irrelevant columns depending the objective

In [ ]:
dff_final = df_final.drop(['App','Price'], axis = 1)

In [ ]:
dff_final.head()

,Rating,Reviews,Type_Paid,Content Rating_Everyone,Content Rating_Everyone 10+,Content Rating_Mature 17+,Content Rating_Teen,Content Rating_Unrated
0,4.1,159,0,1,0,0,0,0
1,3.9,967,0,1,0,0,0,0
2,4.7,87510,0,1,0,0,0,0
3,4.5,215644,0,0,0,0,1,0
4,4.3,967,0,1,0,0,0,0

### 1.3 Min-Max Scaling (Normalization)

In [ ]:
# Scale the numerical features ratings and reviews using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# create an  object
min_max = MinMaxScaler()

df_scaled1 = dff_final.copy()

df_scaled1.iloc[:,:2] = min_max.fit_transform(df_scaled1.iloc[:,:2])
df_scaled1.head()

,Rating,Reviews,Type_Paid,Content Rating_Everyone,Content Rating_Everyone 10+,Content Rating_Mature 17+,Content Rating_Teen,Content Rating_Unrated
0,0.775,0.000002,0,1,0,0,0,0
1,0.725,0.000012,0,1,0,0,0,0
2,0.925,0.001120,0,1,0,0,0,0
3,0.875,0.002759,0,0,0,0,1,0
4,0.825,0.000012,0,1,0,0,0,0

### 1.4 Max absolute scaling

In [ ]:
# Scale only numerical features reviews and ratings using MaxAbsScaler
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()# create an  object

df_scaled2 = dff_final.copy()

df_scaled2.iloc[:,:2] = mas.fit_transform(df_scaled2.iloc[:,:2])
df_scaled2.head()

,Rating,Reviews,Type_Paid,Content Rating_Everyone,Content Rating_Everyone 10+,Content Rating_Mature 17+,Content Rating_Teen,Content Rating_Unrated
0,0.82,0.000002,0,1,0,0,0,0
1,0.78,0.000012,0,1,0,0,0,0
2,0.94,0.001120,0,1,0,0,0,0
3,0.90,0.002759,0,0,0,0,1,0
4,0.86,0.000012,0,1,0,0,0,0

### 1.5 Standard Scaler (Standardization)

In [ ]:
# Scale only numerical features reviews and ratings using StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()# create an  object

df_scaled3 = dff_final.copy()

df_scaled3.iloc[:,:2] = sc.fit_transform(df_scaled3.iloc[:,:2])
df_scaled3.head()

,Rating,Reviews,Type_Paid,Content Rating_Everyone,Content Rating_Everyone 10+,Content Rating_Mature 17+,Content Rating_Teen,Content Rating_Unrated
0,-0.178410,-0.163511,0,1,0,0,0,0
1,-0.566477,-0.163254,0,1,0,0,0,0
2,0.985789,-0.135735,0,1,0,0,0,0
3,0.597723,-0.094991,0,0,0,0,1,0
4,0.209656,-0.163254,0,1,0,0,0,0

-------
## Happy Learning :)
-------