In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/anthonypino/melbourne-housing-market/Melbourne_housing_FULL.csv
/kaggle/input/datasets/anthonypino/melbourne-housing-market/MELBOURNE_HOUSE_PRICES_LESS.csv

In [2]:
print(os.listdir('../input/datasets/anthonypino/melbourne-housing-market'))

['Melbourne_housing_FULL.csv', 'MELBOURNE_HOUSE_PRICES_LESS.csv']

In [3]:
import pandas as pd
nrowsreed=1000
# The path must have NO space between the dots
file_path = '../input/datasets/anthonypino/melbourne-housing-market/Melbourne_housing_FULL.csv'

# Read the data
df = pd.read_csv(file_path, nrows=nrowsreed)

# Preview the data
print(f"Dataset shape: {df.shape}")
df.head()

Dataset shape: (1000, 21)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         1000 non-null   object
 1   Address        1000 non-null   object
 2   Rooms          1000 non-null   int64
 3   Type           1000 non-null   object
 4   Price          785 non-null    float64
 5   Method         1000 non-null   object
 6   SellerG        1000 non-null   object
 7   Date           1000 non-null   object
 8   Distance       1000 non-null   float64
 9   Postcode       1000 non-null   int64
 10  Bedroom2       740 non-null    float64
 11  Bathroom       740 non-null    float64
 12  Car            740 non-null    float64
 13  Landsize       740 non-null    float64
 14  BuildingArea   434 non-null    float64
 15  YearBuilt      476 non-null    float64
 16  CouncilArea    1000 non-null   object
 17  Lattitude      747 non-null    float64
 18  Longtitude     747 non-null    float64
 19  Regionname     1000 non-null   object
 20  Propertycount  1000 non-null   int64
dtypes: float64(10), int64(3), object(8)
memory usage: 164.2+ KB

In [5]:
df.isna().sum()

Suburb             0
Address            0
Rooms              0
Type               0
Price            215
Method             0
SellerG            0
Date               0
Distance           0
Postcode           0
Bedroom2         260
Bathroom         260
Car              260
Landsize         260
BuildingArea     566
YearBuilt        524
CouncilArea        0
Lattitude        253
Longtitude       253
Regionname         0
Propertycount      0
dtype: int64

In [6]:
cols_to_fill_zero = ['Propertycount','Distance','Bedroom2','Bathroom','Car']
df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)

In [7]:
df['Landsize'] = df['Landsize'].fillna(df.Landsize.mean())
df['BuildingArea'].fillna(df.BuildingArea.mean(), inplace=True)

/tmp/ipykernel_17/3463191932.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BuildingArea'].fillna(df.BuildingArea.mean(), inplace=True)

In [8]:
df.isnull().sum()

Suburb             0
Address            0
Rooms              0
Type               0
Price            215
Method             0
SellerG            0
Date               0
Distance           0
Postcode           0
Bedroom2           0
Bathroom           0
Car                0
Landsize           0
BuildingArea       0
YearBuilt        524
CouncilArea        0
Lattitude        253
Longtitude       253
Regionname         0
Propertycount      0
dtype: int64

In [9]:
df.drop(['YearBuilt','Lattitude','Longtitude'], axis='columns', inplace=True)

In [10]:
df.isnull().sum()

Suburb             0
Address            0
Rooms              0
Type               0
Price            215
Method             0
SellerG            0
Date               0
Distance           0
Postcode           0
Bedroom2           0
Bathroom           0
Car                0
Landsize           0
BuildingArea       0
CouncilArea        0
Regionname         0
Propertycount      0
dtype: int64

In [11]:
df = pd.get_dummies(df, drop_first=True)

In [12]:
df.head()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,...,Date_8/10/2016,CouncilArea_Darebin City Council,CouncilArea_Hobsons Bay City Council,CouncilArea_Monash City Council,CouncilArea_Moonee Valley City Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Yarra City Council,Regionname_Southern Metropolitan,Regionname_Western Metropolitan
0,2,NaN,2.5,3067,2.0,1.0,1.0,126.0,157.884793,4019,...,False,False,False,False,False,False,False,True,False,False
1,2,1480000.0,2.5,3067,2.0,1.0,1.0,202.0,157.884793,4019,...,False,False,False,False,False,False,False,True,False,False
2,2,1035000.0,2.5,3067,2.0,1.0,0.0,156.0,79.000000,4019,...,False,False,False,False,False,False,False,True,False,False
3,3,NaN,2.5,3067,3.0,2.0,1.0,0.0,157.884793,4019,...,False,False,False,False,False,False,False,True,False,False
4,3,1465000.0,2.5,3067,3.0,2.0,0.0,134.0,150.000000,4019,...,False,False,False,False,False,False,False,True,False,False

In [13]:
df.dropna(inplace=True)

In [14]:
X = df.drop("Price", axis=1)
y=df['Price']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [16]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [17]:
reg.fit(X_train, y_train)

LinearRegression()

In [18]:
reg.score(X_train, y_train)

1.0

In [19]:
reg.score(X_test, y_test)

0.7158591834671295

It is performing poorly on the test data so let's try using L1 regularization (Lasso regularization) to improve performance

In [20]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg

Lasso(alpha=50, max_iter=100, tol=0.1)

In [21]:
# L1 regularization is adding absolute value to the regression model
lasso_reg.fit(X_train, y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [22]:
lasso_reg.score(X_train, y_train)

0.9985276066972905

In [23]:
lasso_reg.score(X_test, y_test)

0.6829299787127269

It's visible that Lasso regression is not helping in improving the model. let's try L2 regularization in the same model

In [24]:
from sklearn.linear_model import Ridge
rg = Ridge(alpha=50, max_iter=100, tol=0.1)
rg.fit(X_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [25]:
rg.score(X_train, y_train)

0.7234644654352302

In [26]:
rg.score(X_test, y_test)

0.7504938400251102

#### As we tried both regularization method in which L2 regularization is working well.